//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaViviendas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vivienda()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumeroCuartos { get; set; }
        public Nullable<int> NumeroBanos { get; set; }
        public Nullable<decimal> Tamano { get; set; }
        public Nullable<int> NumeroPisos { get; set; }
        public string Accesorios { get; set; }
        public Nullable<int> IdTipoVivienda { get; set; }
        public Nullable<int> IdAgencia { get; set; }

        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }
        [JsonIgnore]
        public virtual TipoVivienda TipoVivienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
